=== chomats/cadse.si-migration/schema/mig.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://www.example.org/mig/" targetNamespace="http://www.example.org/mig/">
    <complexType name="mig-item">
    	<complexContent>
    		<extension base="tns:mig-variable">
    			<attribute name="type" type="string"></attribute>
    		</extension>
    	</complexContent>
    </complexType>
    
    <complexType name="mig-link">
    	<complexContent>
    		<extension base="tns:mig-variable">
    			<attribute name="source" type="string"></attribute>

    			<attribute name="dest" type="string"></attribute>

    			<attribute name="type" type="string"></attribute>

    		</extension>
    	</complexContent>
    </complexType>
    
    <complexType name="mig-context">
    	<sequence>
    		<element name="var" type="tns:mig-variable"
    			maxOccurs="unbounded" minOccurs="0">
    		</element>
    		<element name="var-inst" type="tns:mig-variable"
    			maxOccurs="unbounded" minOccurs="0">
    		</element>
    		<element name="inst" type="tns:mig-inst"
    			maxOccurs="unbounded" minOccurs="0">
    		</element>
    	</sequence>
    	<attribute name="CadseName" type="string" use="required"></attribute>
    	<attribute name="CadseVersion" type="int" use="required"></attribute>
    </complexType>

    <complexType name="mig-variable" abstract="true">
    	<sequence>
    		<element name="conditions" type="tns:mig-condition" maxOccurs="unbounded" minOccurs="0"></element>
    	</sequence>
    	<attribute name="name" type="string"></attribute>
    </complexType>

    <complexType name="mig-condition"></complexType>

    <complexType name="mig-inst" abstract="true">
    </complexType>


    <complexType name="mig-varRef"></complexType>



    
    
    <element name="Migration" >
	    <complexType >
	    	<sequence maxOccurs="unbounded" minOccurs="0">
	    		<element name="cxt" type="tns:mig-context"></element>
	    	</sequence>
	    </complexType>
    </element>

    <complexType name="mig-itemType">
    	<complexContent>
    		<extension base="tns:mig-variable">
    			<attribute name="type-uuid" type="string"></attribute>
    		</extension>
    	</complexContent>
    </complexType>

    <complexType name="mig-linkType">
    	<complexContent>
    		<extension base="tns:mig-variable">
    			<attribute name="source-type" type="string"></attribute>
    			<attribute name="dest-type" type="string"></attribute>
    			<attribute name="linktype-name" type="string"></attribute>
    		</extension>
    	</complexContent>
    </complexType>

    <complexType name="mig-condNoParent">
    	<complexContent>
    		<extension base="tns:mig-condition"></extension>
    	</complexContent>
    </complexType>

    <complexType name="mig-CondHasAttr">
    	<attribute name="keyAttr" type="string"></attribute>
    </complexType>

    <complexType name="mig-InstCreateLink">
    	<complexContent>
    		<extension base="tns:mig-inst">
    			<attribute name="var" type="string"></attribute>
    		</extension>
    	</complexContent>
    </complexType>

    <complexType name="mig-InstDeleteLink">
    	<complexContent>
    		<extension base="tns:mig-inst">
    			<attribute name="var" type="string"></attribute>
    		</extension>
    	</complexContent>
    </complexType>


    <complexType name="mig-InsDuplicateItem">
    	<complexContent>
    		<extension base="tns:mig-inst">
    			<attribute name="var" type="string"></attribute>
    			<attribute name="var-set" type="string"></attribute>
    		</extension>
    	</complexContent>
    </complexType>

    <complexType name="mig-InstDeleteItem">
    	<complexContent>
    		<extension base="tns:mig-inst">
    			<attribute name="var" type="string"></attribute>
    		</extension>
    	</complexContent>
    </complexType>

    <complexType name="mig-cond-NotHasLink">
    	<complexContent>
    		<extension base="tns:mig-condition">
    			<attribute name="lt" type="string"></attribute>
    		</extension>
    	</complexContent>
    </complexType>
</schema>

=== chomats/cadse.si-migration/schema/mig.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Migration xmlns:tns="http://www.example.org/mig/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/mig/ mig.xsd ">
  <cxt CadseName="Model.Workspace.Workspace" CadseVersion="1" >
     <var xsi:type="tns:mig-itemType" type-uuid="Manager" name="M_type"/>
     <var xsi:type="tns:mig-itemType" type-uuid="ItemType" name="IT_type"/>
     <var xsi:type="tns:mig-itemType" type-uuid="CD" name="CD_type"/>
     <var xsi:type="tns:mig-linkType" name="M_type_to_IT_type"  source-type="M_type"  dest-type="IT_type" linktype-name="managers"/>
     <var xsi:type="tns:mig-linkType" name="M_type_to_CD_type"  source-type="M_type"  dest-type="CD_type" linktype-name="xxx"/>
     
     <var xsi:type="tns:mig-item" name="m" type="M_type"/>
     <var xsi:type="tns:mig-item" name="it" type="IT_type"/>
     <var xsi:type="tns:mig-item" name="cd" type="CD_type"/>
     <var xsi:type="tns:mig-link" name="l1" source="m" dest="it" type="M_type_to_IT_type"/>
     <var xsi:type="tns:mig-link" name="l2" source="m" dest="cd" type="M_type_to_CD_type"/>
     
     <var-inst xsi:type="tns:mig-linkType" name="IT_type_to_CD_type"  source-type="IT_type"  dest-type="CD_type" linktype-name="xxx"/>
     <var-inst xsi:type="tns:mig-link" name="l3" source="it" dest="cd" type="IT_type_to_CD_type"/>
     
     <inst xsi:type="tns:mig-InstCreateLink" var="l3"/>
     <inst xsi:type="tns:mig-InstDeleteLink" var="l2"/>
  </cxt>
  <cxt CadseName="Model.Workspace.Workspace" CadseVersion="1" >
   	 <var xsi:type="tns:mig-itemType" type-uuid="Field" name="F_type"/>
     <var xsi:type="tns:mig-itemType" type-uuid="Pages" name="P_type"/>
     <var xsi:type="tns:mig-linkType" name="Pages_to_Field"  
     	source-type="P_type"  dest-type="F_type" linktype-name="fields"/>
    
    
     <var xsi:type="tns:mig-item" name="p" type="P_type"/>
     <var xsi:type="tns:mig-item" name="f" type="F_type"/>
     <var xsi:type="tns:mig-link" name="l_p_to_f" source="p" dest="f" type="Pages_to_Field"/>
     
     <var-inst xsi:type="tns:mig-item" name="f_new"  
     	 type="F_type"/>
     <var-inst xsi:type="tns:mig-link" name="l_p_f_new" source="p" dest="f_new" type="Pages_to_Field"/>
     
     
     <inst xsi:type="tns:mig-InsDuplicateItem" var="f" var-set="f_new"/>
     <inst xsi:type="tns:mig-InstCreateLink" var="l_p_f_new" />
     <inst xsi:type="tns:mig-InstDeleteLink" var="l_p_to_f"/>
     
  </cxt>
  <cxt CadseName="Model.Workspace.Workspace" CadseVersion="1" >
  	<var xsi:type="tns:mig-itemType" type-uuid="Field" name="F_type2"/>
    <var xsi:type="tns:mig-item" name="f2" type="F_type2">
	    <conditions xsi:type="tns:mig-condNoParent"/>
    </var>
    <inst xsi:type="tns:mig-InstDeleteItem" var="f2"/>  
  </cxt>
</tns:Migration>
